Fix unsupported asyncio syntax
QubesOS/qubes-app-shutdown-idle pull request #21
Opened 2023-01-10 14:17 UTC by marmarta

Wrap coroutines into explicit tasks.

fixes QubesOS/qubes-issues#7979

2023-01-11 15:54 UTC, marmarta commented
PipelineRetryFailed

2023-01-12 14:23 UTC, marmarta commented
PipelineRetry

2023-01-12 16:38 UTC, marmarek commented
See https://github.com/QubesOS/qubes-core-admin/pull/508#issuecomment-1380686332

2023-01-12 22:48 UTC, DemiMarie requested changes

2023-01-12 22:48 UTC, DemiMarie commented on qubesidle/idleness_monitor.py
> +                tasks.append(asyncio.Task(w.wait_for_state_change()))
```suggestion
                tasks.append(asyncio.create_task(w.wait_for_state_change()))
```

2023-01-13 14:11 UTC, marmarta commented on qubesidle/idleness_monitor.py
> +                tasks.append(asyncio.Task(w.wait_for_state_change()))
Thanks!

2023-01-13 22:51 UTC, DemiMarie approved these changes

2023-01-13 22:51 UTC, DemiMarie commented on qubesidle/idleness_monitor.py
> +                tasks.append(asyncio.Task(w.wait_for_state_change()))
You’re welcome!

2023-01-16 17:46 UTC, marmarek commented
The same needs to be fixed in tests too (see https://gitlab.com/QubesOS/qubes-app-shutdown-idle/-/jobs/3600375702 for example).

2023-01-17 15:37 UTC, marmarta commented
PipelineRetryFailed

2023-01-17 16:30 UTC, marmarta commented
centos fails for some weird reason, but it doesn't look like my fault. Tests are fixed, though

2023-01-19 13:25 UTC, merged